
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Oct 30 12:30:32 CST 2024
//----------------------------------------------------

package com.compi.scanner;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Llave_c = 32;
  public static final int Op_booleano = 22;
  public static final int Llave_a = 31;
  public static final int If = 11;
  public static final int Void = 17;
  public static final int Default = 7;
  public static final int If_else = 23;
  public static final int Else = 9;
  public static final int Read = 19;
  public static final int Break = 2;
  public static final int Corchete_c = 34;
  public static final int Corchete_a = 33;
  public static final int Long = 13;
  public static final int Tipo_dato = 26;
  public static final int Return = 14;
  public static final int While = 18;
  public static final int Int = 12;
  public static final int Cadena = 27;
  public static final int Parentesis_c = 30;
  public static final int Parentesis_a = 29;
  public static final int For = 10;
  public static final int P_coma = 36;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Switch = 16;
  public static final int Linea = 24;
  public static final int Char = 4;
  public static final int ERROR = 38;
  public static final int Do = 8;
  public static final int Continue = 6;
  public static final int Case = 3;
  public static final int Short = 15;
  public static final int Const = 5;
  public static final int Identificador = 37;
  public static final int Write = 20;
  public static final int Main = 35;
  public static final int Igual = 28;
  public static final int Op_aritmetrico = 21;
  public static final int Comillas = 25;
}

