// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: C:/Users/ncque/Downloads/tec/ci/Scanner/Scanner/src/main/java/com/compi/scanner/LexerCup.flex

package com.compi.scanner;
import java_cup.runtime.Symbol;

@SuppressWarnings("fallthrough")
class LexerCup implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\1\1\5"+
    "\1\6\1\7\1\0\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\7\24"+
    "\2\25\1\26\1\27\1\30\1\31\1\32\2\0\3\33"+
    "\1\34\1\35\1\34\5\36\1\37\13\36\1\40\2\36"+
    "\1\0\1\41\2\0\1\36\1\0\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\36\1\53"+
    "\1\54\1\36\1\55\1\56\2\36\1\57\1\60\1\61"+
    "\1\62\1\63\1\64\1\40\2\36\1\65\1\66\1\67"+
    "\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\2\1"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\1\1\15"+
    "\2\16\1\17\1\20\1\21\1\22\1\23\16\24\1\25"+
    "\1\1\1\26\1\27\1\30\1\0\1\5\1\31\1\32"+
    "\1\33\1\0\1\34\1\35\1\36\1\37\2\16\1\40"+
    "\1\41\1\42\1\2\1\43\1\44\1\0\1\16\1\45"+
    "\1\0\1\16\2\0\1\16\2\46\1\16\1\47\1\50"+
    "\1\51\5\24\1\52\4\24\1\53\10\24\1\54\1\0"+
    "\1\31\2\0\1\16\1\0\1\16\1\0\1\16\1\0"+
    "\1\42\1\55\2\0\1\56\2\0\1\57\1\16\1\41"+
    "\1\46\1\56\1\46\7\24\1\60\1\24\1\61\7\24"+
    "\1\62\1\55\1\0\1\16\1\0\1\2\1\0\1\55"+
    "\1\0\1\55\1\0\1\55\1\16\1\55\1\46\1\24"+
    "\1\63\1\64\3\24\1\65\2\24\1\66\1\24\1\67"+
    "\1\24\1\70\1\71\1\24\1\55\1\0\1\55\1\16"+
    "\1\2\1\42\1\16\1\55\1\72\1\73\2\24\1\74"+
    "\3\24\1\75\1\16\1\44\2\24\1\76\1\77\1\100"+
    "\1\24\1\101\1\102";

  private static int [] zzUnpackAction() {
    int [] result = new int[193];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\250\0\340\0\u0118\0\70\0\u0150"+
    "\0\u0188\0\70\0\70\0\u01c0\0\u01f8\0\70\0\u0230\0\u0268"+
    "\0\u02a0\0\u02d8\0\u0310\0\70\0\70\0\u0348\0\u0380\0\u03b8"+
    "\0\u03f0\0\u0428\0\u0460\0\u0498\0\u04d0\0\u0508\0\u0540\0\u0578"+
    "\0\u05b0\0\u05e8\0\u0620\0\u0658\0\u0690\0\u06c8\0\70\0\u0700"+
    "\0\70\0\70\0\70\0\u0738\0\u0770\0\u07a8\0\70\0\u07e0"+
    "\0\u0818\0\70\0\70\0\70\0\70\0\u0850\0\u0888\0\70"+
    "\0\u0268\0\u08c0\0\u08f8\0\70\0\70\0\u0930\0\u0968\0\u09a0"+
    "\0\u09d8\0\u0a10\0\u0a48\0\u0a80\0\u0ab8\0\u0af0\0\u0b28\0\u0b60"+
    "\0\70\0\70\0\70\0\u0b98\0\u0bd0\0\u0c08\0\u0c40\0\u0c78"+
    "\0\u03f0\0\u0cb0\0\u0ce8\0\u0d20\0\u0d58\0\u03f0\0\u0d90\0\u0dc8"+
    "\0\u0e00\0\u0e38\0\u0e70\0\u0ea8\0\u0ee0\0\u0f18\0\70\0\u0f50"+
    "\0\70\0\u0f88\0\u0fc0\0\u0ff8\0\u1030\0\u1068\0\u10a0\0\u10d8"+
    "\0\u1110\0\u1148\0\u1180\0\u11b8\0\u11f0\0\70\0\u1228\0\u1260"+
    "\0\u1298\0\u12d0\0\u1308\0\u1340\0\u0af0\0\u1378\0\u13b0\0\u13e8"+
    "\0\u1420\0\u1458\0\u1490\0\u14c8\0\u1500\0\u03f0\0\u1538\0\u03f0"+
    "\0\u1570\0\u15a8\0\u15e0\0\u1618\0\u1650\0\u1688\0\u16c0\0\70"+
    "\0\u16f8\0\u1730\0\u1768\0\u17a0\0\u17d8\0\u0268\0\u1810\0\u1848"+
    "\0\u1880\0\u18b8\0\u18f0\0\u1928\0\u1960\0\u1998\0\u19d0\0\u03f0"+
    "\0\u03f0\0\u1a08\0\u1a40\0\u1a78\0\u03f0\0\u1ab0\0\u1ae8\0\u03f0"+
    "\0\u1b20\0\u03f0\0\u1b58\0\u03f0\0\u03f0\0\u1b90\0\70\0\u1bc8"+
    "\0\u1c00\0\u1c38\0\70\0\u17d8\0\u1c70\0\u1ca8\0\u03f0\0\u03f0"+
    "\0\u1ce0\0\u1d18\0\u03f0\0\u1d50\0\u1d88\0\u1dc0\0\u03f0\0\u1df8"+
    "\0\u1848\0\u1e30\0\u1e68\0\u03f0\0\u03f0\0\u03f0\0\u1ea0\0\u03f0"+
    "\0\u03f0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[193];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\2\23\1\24\1\25\1\26\1\27"+
    "\1\30\6\31\1\2\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\31\1\40\1\31\1\41\2\31\1\42"+
    "\1\43\1\44\1\31\1\45\1\46\1\47\1\50\1\51"+
    "\71\0\2\3\1\0\1\3\114\0\1\52\36\0\2\5"+
    "\1\0\3\5\1\53\32\5\1\54\26\5\1\55\2\0"+
    "\1\55\1\0\17\55\2\56\42\55\11\0\1\57\56\0"+
    "\2\60\1\0\7\60\1\0\26\60\1\61\26\60\31\0"+
    "\1\62\54\0\1\63\12\0\1\64\56\0\1\65\2\0"+
    "\1\66\2\67\3\0\1\70\61\0\3\71\57\0\1\72"+
    "\4\0\1\73\6\0\1\74\56\0\1\75\1\76\1\0"+
    "\2\77\1\100\7\0\1\101\1\0\1\102\1\103\5\0"+
    "\1\101\5\0\1\102\33\0\1\75\1\104\1\0\3\105"+
    "\5\0\2\106\1\107\1\106\1\110\1\106\1\0\4\106"+
    "\1\107\5\106\1\110\10\106\34\0\1\111\67\0\1\112"+
    "\67\0\1\113\61\0\3\31\5\0\6\31\1\0\23\31"+
    "\26\0\3\31\5\0\6\31\1\0\15\31\1\114\5\31"+
    "\26\0\3\31\5\0\6\31\1\0\1\115\6\31\1\116"+
    "\4\31\1\117\6\31\26\0\3\31\5\0\6\31\1\0"+
    "\4\31\1\120\7\31\1\121\6\31\26\0\3\31\5\0"+
    "\6\31\1\0\12\31\1\122\10\31\26\0\3\31\5\0"+
    "\6\31\1\0\1\123\13\31\1\124\6\31\26\0\3\31"+
    "\5\0\6\31\1\0\12\31\1\125\10\31\26\0\3\31"+
    "\5\0\6\31\1\0\5\31\1\126\5\31\1\127\7\31"+
    "\26\0\3\31\5\0\6\31\1\0\14\31\1\130\6\31"+
    "\26\0\3\31\5\0\6\31\1\0\4\31\1\131\16\31"+
    "\26\0\3\31\5\0\6\31\1\0\7\31\1\132\12\31"+
    "\1\133\26\0\3\31\5\0\6\31\1\0\15\31\1\134"+
    "\5\31\26\0\3\31\5\0\6\31\1\0\14\31\1\135"+
    "\6\31\26\0\3\31\5\0\6\31\1\0\7\31\1\136"+
    "\13\31\71\0\1\137\1\0\2\5\3\0\63\5\1\55"+
    "\2\0\1\55\1\0\64\55\2\0\1\55\1\0\16\55"+
    "\3\56\42\55\2\140\1\0\7\140\1\141\26\140\1\142"+
    "\30\140\3\0\1\140\1\60\3\140\1\60\10\140\1\60"+
    "\15\140\1\60\13\140\1\60\1\140\1\60\1\140\1\60"+
    "\6\140\21\0\1\143\1\0\2\144\1\145\11\0\1\146"+
    "\1\147\13\0\1\146\34\0\1\143\1\0\3\150\11\0"+
    "\1\146\14\0\1\146\13\0\2\72\1\151\1\72\1\151"+
    "\10\72\1\152\52\72\2\73\3\0\63\73\23\0\3\153"+
    "\62\0\1\75\1\76\1\0\2\77\1\100\7\0\1\154"+
    "\1\0\1\102\6\0\1\154\5\0\1\102\34\0\1\155"+
    "\1\0\3\100\7\0\1\154\10\0\1\154\21\0\16\156"+
    "\1\0\1\156\1\0\2\156\3\0\42\156\20\0\1\75"+
    "\1\157\1\0\3\160\42\0\23\161\3\162\5\161\3\162"+
    "\4\161\6\162\20\161\23\163\3\153\42\163\20\0\1\75"+
    "\1\104\1\0\3\105\5\0\2\106\1\164\1\106\1\110"+
    "\1\106\1\0\4\106\1\164\5\106\1\110\10\106\26\0"+
    "\3\106\5\0\6\106\1\0\23\106\3\0\16\156\1\0"+
    "\1\156\1\0\2\156\3\106\5\156\6\165\1\156\23\165"+
    "\3\156\20\0\1\75\1\157\1\0\3\166\5\0\6\106"+
    "\1\0\23\106\26\0\3\31\5\0\6\31\1\0\4\31"+
    "\1\167\16\31\26\0\3\31\5\0\6\31\1\0\16\31"+
    "\1\170\4\31\26\0\3\31\5\0\6\31\1\0\1\171"+
    "\22\31\26\0\3\31\5\0\6\31\1\0\13\31\1\172"+
    "\7\31\26\0\3\31\5\0\6\31\1\0\5\31\1\173"+
    "\15\31\26\0\3\31\5\0\6\31\1\0\16\31\1\174"+
    "\4\31\26\0\3\31\5\0\6\31\1\0\12\31\1\175"+
    "\10\31\26\0\3\31\5\0\6\31\1\0\15\31\1\176"+
    "\5\31\26\0\3\31\5\0\6\31\1\0\14\31\1\177"+
    "\6\31\26\0\3\31\5\0\6\31\1\0\17\31\1\200"+
    "\3\31\26\0\3\31\5\0\6\31\1\0\13\31\1\201"+
    "\7\31\26\0\3\31\5\0\6\31\1\0\17\31\1\202"+
    "\3\31\26\0\3\31\5\0\6\31\1\0\14\31\1\203"+
    "\6\31\26\0\3\31\5\0\6\31\1\0\10\31\1\204"+
    "\12\31\26\0\3\31\5\0\6\31\1\0\20\31\1\205"+
    "\2\31\26\0\3\31\5\0\6\31\1\0\10\31\1\206"+
    "\12\31\26\0\3\31\5\0\6\31\1\0\10\31\1\207"+
    "\12\31\3\0\2\140\1\0\7\140\1\210\26\140\1\142"+
    "\30\140\3\0\63\140\23\0\3\211\63\0\1\143\1\0"+
    "\2\144\1\145\7\0\1\212\1\0\1\146\6\0\1\212"+
    "\5\0\1\146\36\0\3\145\7\0\1\212\10\0\1\212"+
    "\42\0\1\143\1\0\3\145\65\0\3\213\5\0\3\213"+
    "\4\0\6\213\41\0\1\143\1\0\3\150\7\0\1\212"+
    "\1\0\1\146\6\0\1\212\5\0\1\146\13\0\15\151"+
    "\1\214\52\151\2\72\1\151\1\72\1\151\10\72\1\152"+
    "\4\72\1\215\45\72\20\0\1\75\1\216\1\0\3\153"+
    "\6\0\1\217\1\154\7\0\1\217\1\154\1\217\36\0"+
    "\1\220\1\0\1\220\2\0\3\221\65\0\3\222\65\0"+
    "\3\223\65\0\3\160\7\0\1\154\10\0\1\154\21\0"+
    "\23\161\3\0\5\161\3\0\4\161\6\0\20\161\20\0"+
    "\1\75\1\157\1\0\3\224\5\0\3\162\1\0\1\102"+
    "\2\0\6\162\4\0\1\102\13\0\23\163\3\0\42\163"+
    "\16\156\1\220\1\156\1\220\2\156\3\225\5\156\6\165"+
    "\1\156\23\165\3\156\23\0\3\166\5\0\2\106\1\226"+
    "\3\106\1\0\4\106\1\226\16\106\26\0\3\31\5\0"+
    "\6\31\1\0\1\227\22\31\26\0\3\31\5\0\6\31"+
    "\1\0\4\31\1\230\16\31\26\0\3\31\5\0\6\31"+
    "\1\0\15\31\1\231\5\31\26\0\3\31\5\0\6\31"+
    "\1\0\16\31\1\232\1\233\3\31\26\0\3\31\5\0"+
    "\6\31\1\0\1\234\22\31\26\0\3\31\5\0\6\31"+
    "\1\0\4\31\1\235\16\31\26\0\3\31\5\0\6\31"+
    "\1\0\16\31\1\236\4\31\26\0\3\31\5\0\6\31"+
    "\1\0\1\31\1\237\21\31\26\0\3\31\5\0\6\31"+
    "\1\0\6\31\1\240\14\31\26\0\3\31\5\0\6\31"+
    "\1\0\20\31\1\241\2\31\26\0\3\31\5\0\6\31"+
    "\1\0\17\31\1\242\3\31\26\0\3\31\5\0\6\31"+
    "\1\0\17\31\1\243\3\31\26\0\3\31\5\0\6\31"+
    "\1\0\4\31\1\244\16\31\26\0\3\31\5\0\6\31"+
    "\1\0\3\31\1\245\17\31\26\0\3\31\5\0\6\31"+
    "\1\0\12\31\1\246\10\31\26\0\3\211\6\0\1\247"+
    "\1\212\7\0\1\247\1\212\1\247\36\0\1\250\1\0"+
    "\1\250\2\0\3\251\63\0\1\143\1\0\3\252\5\0"+
    "\3\213\1\0\1\146\2\0\6\213\4\0\1\146\13\0"+
    "\15\151\1\214\4\151\1\253\45\151\2\254\1\0\1\254"+
    "\1\0\63\254\20\0\1\75\72\0\3\221\62\0\1\75"+
    "\2\0\3\221\6\0\1\217\10\0\1\217\1\0\1\217"+
    "\41\0\1\216\1\0\3\222\62\0\1\75\2\0\3\223"+
    "\6\0\1\217\1\154\7\0\1\217\1\154\1\217\40\0"+
    "\1\75\1\157\1\0\3\224\5\0\2\162\1\255\1\0"+
    "\1\102\2\0\4\162\1\255\1\162\4\0\1\102\33\0"+
    "\1\75\2\0\3\225\5\0\1\106\1\256\4\106\1\0"+
    "\3\106\1\256\1\106\1\256\15\106\21\0\1\220\1\0"+
    "\1\220\2\0\3\225\5\0\6\106\1\0\23\106\26\0"+
    "\3\31\5\0\6\31\1\0\11\31\1\257\11\31\26\0"+
    "\3\31\5\0\6\31\1\0\17\31\1\260\3\31\26\0"+
    "\3\31\5\0\6\31\1\0\10\31\1\261\12\31\26\0"+
    "\3\31\5\0\6\31\1\0\20\31\1\262\2\31\26\0"+
    "\3\31\5\0\6\31\1\0\4\31\1\263\16\31\26\0"+
    "\3\31\5\0\6\31\1\0\1\264\22\31\26\0\3\31"+
    "\5\0\6\31\1\0\15\31\1\265\5\31\26\0\3\31"+
    "\5\0\6\31\1\0\2\31\1\266\20\31\26\0\3\31"+
    "\5\0\6\31\1\0\4\31\1\267\16\31\26\0\3\251"+
    "\65\0\3\251\6\0\1\247\10\0\1\247\1\0\1\247"+
    "\41\0\1\143\1\0\3\252\5\0\2\213\1\270\1\0"+
    "\1\146\2\0\4\213\1\270\1\213\4\0\1\146\31\0"+
    "\1\220\1\0\1\271\1\157\1\0\3\224\5\0\3\162"+
    "\1\0\1\102\2\0\6\162\4\0\1\102\33\0\1\75"+
    "\2\0\3\106\5\0\6\106\1\0\23\106\26\0\3\31"+
    "\5\0\6\31\1\0\13\31\1\272\7\31\26\0\3\31"+
    "\5\0\6\31\1\0\12\31\1\273\10\31\26\0\3\31"+
    "\5\0\6\31\1\0\12\31\1\274\10\31\26\0\3\31"+
    "\5\0\6\31\1\0\13\31\1\275\7\31\26\0\3\31"+
    "\5\0\6\31\1\0\7\31\1\276\13\31\21\0\1\250"+
    "\1\0\1\250\1\143\1\0\3\252\5\0\3\213\1\0"+
    "\1\146\2\0\6\213\4\0\1\146\36\0\3\31\5\0"+
    "\6\31\1\0\20\31\1\277\2\31\26\0\3\31\5\0"+
    "\6\31\1\0\17\31\1\300\3\31\26\0\3\31\5\0"+
    "\6\31\1\0\4\31\1\301\16\31\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[7896];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\1\11\2\1\2\11\2\1\1\11"+
    "\5\1\2\11\21\1\1\11\1\1\3\11\1\0\2\1"+
    "\1\11\1\1\1\0\4\11\2\1\1\11\3\1\2\11"+
    "\1\0\2\1\1\0\1\1\2\0\4\1\3\11\23\1"+
    "\1\11\1\0\1\11\2\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\2\1\2\0\1\11\2\0\27\1\1\11"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\24\1\1\11\1\0\2\1\1\11\26\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[193];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  private void reportError(String message) {
    System.err.println("Error léxico en línea " + (yyline + 1) + ", columna " + (yycolumn + 1) + ": " + message);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexerCup(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { reportError("Desconocido -> " + yytext());
            }
          // fall through
          case 67: break;
          case 2:
            { /* ignore */
            }
          // fall through
          case 68: break;
          case 3:
            { return new Symbol(sym.NOT, yyline, (int) yychar, yytext());
            }
          // fall through
          case 69: break;
          case 4:
            { reportError("String no cerrado -> " + yytext());
            }
          // fall through
          case 70: break;
          case 5:
            { reportError("Caracter invalido -> " + yytext());
            }
          // fall through
          case 71: break;
          case 6:
            { return new Symbol(sym.MOD, yyline, (int) yychar, yytext());
            }
          // fall through
          case 72: break;
          case 7:
            { return new Symbol(sym.LPAREN, yyline, (int) yychar, yytext());
            }
          // fall through
          case 73: break;
          case 8:
            { return new Symbol(sym.RPAREN, yyline, (int) yychar, yytext());
            }
          // fall through
          case 74: break;
          case 9:
            { return new Symbol(sym.TIMES, yyline, (int) yychar, yytext());
            }
          // fall through
          case 75: break;
          case 10:
            { return new Symbol(sym.PLUS, yyline, (int) yychar, yytext());
            }
          // fall through
          case 76: break;
          case 11:
            { return new Symbol(sym.COMMA, yyline, (int) yychar, yytext());
            }
          // fall through
          case 77: break;
          case 12:
            { return new Symbol(sym.MINUS, yyline, (int) yychar, yytext());
            }
          // fall through
          case 78: break;
          case 13:
            { return new Symbol(sym.DIV, yyline, (int) yychar, yytext());
            }
          // fall through
          case 79: break;
          case 14:
            { return new Symbol(sym.INT, yyline, (int) yychar, yytext());
            }
          // fall through
          case 80: break;
          case 15:
            { return new Symbol(sym.COLON, yyline, (int) yychar, yytext());
            }
          // fall through
          case 81: break;
          case 16:
            { return new Symbol(sym.SEMI, yyline, (int) yychar, yytext());
            }
          // fall through
          case 82: break;
          case 17:
            { return new Symbol(sym.LT, yyline, (int) yychar, yytext());
            }
          // fall through
          case 83: break;
          case 18:
            { return new Symbol(sym.EQ, yyline, (int) yychar, yytext());
            }
          // fall through
          case 84: break;
          case 19:
            { return new Symbol(sym.GT, yyline, (int) yychar, yytext());
            }
          // fall through
          case 85: break;
          case 20:
            { return new Symbol(sym.ID, yyline, (int) yychar, yytext());
            }
          // fall through
          case 86: break;
          case 21:
            { return new Symbol(sym.LBRACKET, yyline, (int) yychar, yytext());
            }
          // fall through
          case 87: break;
          case 22:
            { return new Symbol(sym.RBRACKET, yyline, (int) yychar, yytext());
            }
          // fall through
          case 88: break;
          case 23:
            { return new Symbol(sym.NOT_EQ, yyline, (int) yychar, yytext());
            }
          // fall through
          case 89: break;
          case 24:
            { return new Symbol(sym.STRING, yyline, (int) yychar, yytext());
            }
          // fall through
          case 90: break;
          case 25:
            { return new Symbol(sym.CHAR, yyline, (int) yychar, yytext());
            }
          // fall through
          case 91: break;
          case 26:
            { return new Symbol(sym.AND, yyline, (int) yychar, yytext());
            }
          // fall through
          case 92: break;
          case 27:
            { reportError("Caracter no cerrado -> " + yytext());
            }
          // fall through
          case 93: break;
          case 28:
            { return new Symbol(sym.TIMES_EQ, yyline, (int) yychar, yytext());
            }
          // fall through
          case 94: break;
          case 29:
            { return new Symbol(sym.PLUS_PLUS, yyline, (int) yychar, yytext());
            }
          // fall through
          case 95: break;
          case 30:
            { return new Symbol(sym.PLUS_EQ, yyline, (int) yychar, yytext());
            }
          // fall through
          case 96: break;
          case 31:
            { return new Symbol(sym.MINUS_MINUS, yyline, (int) yychar, yytext());
            }
          // fall through
          case 97: break;
          case 32:
            { return new Symbol(sym.MINUS_EQ, yyline, (int) yychar, yytext());
            }
          // fall through
          case 98: break;
          case 33:
            { reportError("Flotante mal formado -> " + yytext());
            }
          // fall through
          case 99: break;
          case 34:
            { reportError("Comentario no cerrado -> " + yytext());
            }
          // fall through
          case 100: break;
          case 35:
            { return new Symbol(sym.DIV_EQ, yyline, (int) yychar, yytext());
            }
          // fall through
          case 101: break;
          case 36:
            { reportError("Símbolo inválido después de número -> " + yytext());
            }
          // fall through
          case 102: break;
          case 37:
            { reportError("Octal mal formado -> " + yytext());
            }
          // fall through
          case 103: break;
          case 38:
            { reportError("Identificador no puede empezar con un número -> " + yytext());
            }
          // fall through
          case 104: break;
          case 39:
            { return new Symbol(sym.LT_EQ, yyline, (int) yychar, yytext());
            }
          // fall through
          case 105: break;
          case 40:
            { return new Symbol(sym.EQ_EQ, yyline, (int) yychar, yytext());
            }
          // fall through
          case 106: break;
          case 41:
            { return new Symbol(sym.GT_EQ, yyline, (int) yychar, yytext());
            }
          // fall through
          case 107: break;
          case 42:
            { return new Symbol(sym.DO, yyline, (int) yychar, yytext());
            }
          // fall through
          case 108: break;
          case 43:
            { return new Symbol(sym.IF, yyline, (int) yychar, yytext());
            }
          // fall through
          case 109: break;
          case 44:
            { return new Symbol(sym.OR, yyline, (int) yychar, yytext());
            }
          // fall through
          case 110: break;
          case 45:
            { return new Symbol(sym.FLOAT, yyline, (int) yychar, yytext());
            }
          // fall through
          case 111: break;
          case 46:
            { reportError("Exponente mal formado -> " + yytext());
            }
          // fall through
          case 112: break;
          case 47:
            { reportError("Hexadecimal mal formado -> " + yytext());
            }
          // fall through
          case 113: break;
          case 48:
            { return new Symbol(sym.FOR, yyline, (int) yychar, yytext());
            }
          // fall through
          case 114: break;
          case 49:
            { return new Symbol(sym.TYPE_INT, yyline, (int) yychar, yytext());
            }
          // fall through
          case 115: break;
          case 50:
            { reportError("Caracter mal formado -> " + yytext());
            }
          // fall through
          case 116: break;
          case 51:
            { return new Symbol(sym.CASE, yyline, (int) yychar, yytext());
            }
          // fall through
          case 117: break;
          case 52:
            { return new Symbol(sym.TYPE_CHAR, yyline, (int) yychar, yytext());
            }
          // fall through
          case 118: break;
          case 53:
            { return new Symbol(sym.ELSE, yyline, (int) yychar, yytext());
            }
          // fall through
          case 119: break;
          case 54:
            { return new Symbol(sym.TYPE_LONG, yyline, (int) yychar, yytext());
            }
          // fall through
          case 120: break;
          case 55:
            { return new Symbol(sym.TYPE_SHORT, yyline, (int) yychar, yytext());
            }
          // fall through
          case 121: break;
          case 56:
            { return new Symbol(sym.TRUE, yyline, (int) yychar, yytext());
            }
          // fall through
          case 122: break;
          case 57:
            { return new Symbol(sym.VOID, yyline, (int) yychar, yytext());
            }
          // fall through
          case 123: break;
          case 58:
            { return new Symbol(sym.BREAK, yyline, (int) yychar, yytext());
            }
          // fall through
          case 124: break;
          case 59:
            { return new Symbol(sym.CONST, yyline, (int) yychar, yytext());
            }
          // fall through
          case 125: break;
          case 60:
            { return new Symbol(sym.FALSE, yyline, (int) yychar, yytext());
            }
          // fall through
          case 126: break;
          case 61:
            { return new Symbol(sym.WHILE, yyline, (int) yychar, yytext());
            }
          // fall through
          case 127: break;
          case 62:
            { return new Symbol(sym.GLOBAL, yyline, (int) yychar, yytext());
            }
          // fall through
          case 128: break;
          case 63:
            { return new Symbol(sym.RETURN, yyline, (int) yychar, yytext());
            }
          // fall through
          case 129: break;
          case 64:
            { return new Symbol(sym.SWITCH, yyline, (int) yychar, yytext());
            }
          // fall through
          case 130: break;
          case 65:
            { return new Symbol(sym.DEFAULT, yyline, (int) yychar, yytext());
            }
          // fall through
          case 131: break;
          case 66:
            { return new Symbol(sym.CONTINUE, yyline, (int) yychar, yytext());
            }
          // fall through
          case 132: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
