// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: Scanner/src/main/java/com/compi/scanner/SimpleLexer.flex

/* Simple JFlex example to tokenize arithmetic expressions */

package com.compi.scanner;
import static com.compi.scanner.TokenTypes.*;

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class SimpleLexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\1\1\5"+
    "\1\6\1\7\1\0\1\5\1\10\1\0\2\11\1\12"+
    "\1\13\1\11\1\14\1\15\1\16\1\17\7\20\2\21"+
    "\2\11\1\22\1\23\1\24\1\11\1\0\3\25\1\26"+
    "\1\27\1\26\5\30\1\31\13\30\1\32\2\30\1\11"+
    "\1\33\1\11\1\5\1\30\1\0\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\30\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\30\1\53\1\54"+
    "\1\55\1\56\1\57\1\60\1\61\1\62\1\63\1\11"+
    "\1\64\2\11\6\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\5\3\2\6"+
    "\2\3\20\7\1\3\2\4\1\0\1\6\1\4\1\5"+
    "\1\6\1\10\1\2\1\0\1\6\1\11\1\0\1\6"+
    "\2\0\1\6\2\12\1\6\6\7\1\13\4\7\1\13"+
    "\13\7\1\0\1\6\1\4\1\6\1\0\1\4\1\0"+
    "\2\14\1\0\1\10\1\6\2\0\1\15\1\16\1\6"+
    "\1\17\1\12\1\15\1\12\30\7\1\6\1\0\1\4"+
    "\1\14\1\0\1\2\1\0\3\6\1\12\16\7\1\14"+
    "\1\2\1\10\2\6\11\7";

  private static int [] zzUnpackAction() {
    int [] result = new int[159];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\324\0\u0109\0\u013e\0\65"+
    "\0\u0173\0\u01a8\0\u01dd\0\u0212\0\u0247\0\u027c\0\u02b1\0\u02e6"+
    "\0\u031b\0\u0350\0\u0385\0\u03ba\0\u03ef\0\u0424\0\u0459\0\u048e"+
    "\0\u04c3\0\u04f8\0\u052d\0\u0562\0\u0597\0\u05cc\0\u0601\0\u0636"+
    "\0\u066b\0\u06a0\0\u06d5\0\u070a\0\u073f\0\u0774\0\u07a9\0\u07de"+
    "\0\u0813\0\u0848\0\u087d\0\u08b2\0\u08e7\0\u091c\0\u0951\0\u0986"+
    "\0\u09bb\0\u09f0\0\u0a25\0\u0a5a\0\u0a8f\0\u0ac4\0\u0af9\0\u0b2e"+
    "\0\u0b63\0\u0b98\0\u0bcd\0\u0c02\0\u0c37\0\u0c6c\0\u0ca1\0\u02e6"+
    "\0\u0cd6\0\u0d0b\0\u0d40\0\u0d75\0\u0daa\0\u0ddf\0\u0e14\0\u0e49"+
    "\0\u0e7e\0\u0eb3\0\u0ee8\0\u0f1d\0\u0f52\0\u0f87\0\65\0\u0fbc"+
    "\0\u070a\0\u0ff1\0\u070a\0\u066b\0\u1026\0\u105b\0\u1090\0\u10c5"+
    "\0\u10fa\0\65\0\u112f\0\u1164\0\u1199\0\u11ce\0\u09f0\0\u1203"+
    "\0\u1238\0\u126d\0\u12a2\0\u12d7\0\u130c\0\u1341\0\u1376\0\u13ab"+
    "\0\u13e0\0\u1415\0\u144a\0\u147f\0\u14b4\0\u14e9\0\u151e\0\u1553"+
    "\0\u1588\0\u15bd\0\u15f2\0\u1627\0\u165c\0\u1691\0\u16c6\0\u16fb"+
    "\0\u0ff1\0\u1730\0\u0f52\0\u0ff1\0\u1765\0\u179a\0\u17cf\0\u1804"+
    "\0\u1839\0\u186e\0\u18a3\0\u18d8\0\u190d\0\u1942\0\u1977\0\u19ac"+
    "\0\u19e1\0\u1a16\0\u1a4b\0\u1a80\0\u1ab5\0\u1aea\0\u1b1f\0\u1b54"+
    "\0\u1b89\0\u0f1d\0\65\0\u179a\0\u1bbe\0\u09f0\0\u1bf3\0\u1c28"+
    "\0\u1c5d\0\u1c92\0\u1cc7\0\u1cfc\0\u1d31\0\u1d66\0\u1d9b";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[159];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\4\1\11\1\12\1\10\1\13\1\14\2\15"+
    "\1\16\1\4\1\17\6\20\1\2\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\20\1\30\1\20\1\31"+
    "\4\20\1\32\1\33\1\34\1\35\1\36\1\37\3\20"+
    "\1\40\66\0\2\3\1\0\1\3\103\0\1\10\41\0"+
    "\2\41\1\0\1\42\1\43\1\41\1\44\24\41\1\45"+
    "\31\41\1\46\2\0\1\46\1\0\13\46\2\47\43\46"+
    "\10\0\1\10\12\0\1\10\54\0\1\10\7\0\1\10"+
    "\55\0\1\10\6\0\2\10\52\0\1\50\3\0\1\51"+
    "\4\0\1\10\56\0\1\52\1\0\2\53\1\54\5\0"+
    "\1\55\1\0\1\56\1\57\5\0\1\55\5\0\1\56"+
    "\12\0\1\57\20\0\1\60\1\0\3\61\3\0\2\62"+
    "\1\63\1\62\1\64\1\62\1\0\4\62\1\63\5\62"+
    "\1\64\15\62\23\0\1\4\1\10\64\0\1\10\1\4"+
    "\57\0\3\20\3\0\6\20\1\0\30\20\20\0\3\20"+
    "\3\0\6\20\1\0\22\20\1\65\5\20\20\0\3\20"+
    "\3\0\6\20\1\0\17\20\1\66\10\20\20\0\3\20"+
    "\3\0\6\20\1\0\1\67\6\20\1\70\5\20\1\71"+
    "\12\20\20\0\3\20\3\0\6\20\1\0\4\20\1\72"+
    "\10\20\1\73\12\20\20\0\3\20\3\0\6\20\1\0"+
    "\12\20\1\67\1\20\1\74\10\20\1\75\2\20\20\0"+
    "\3\20\3\0\6\20\1\0\12\20\1\76\2\20\1\77"+
    "\12\20\20\0\3\20\3\0\6\20\1\0\15\20\1\65"+
    "\12\20\20\0\3\20\3\0\6\20\1\0\5\20\1\100"+
    "\6\20\1\101\13\20\20\0\3\20\3\0\6\20\1\0"+
    "\15\20\1\102\12\20\20\0\3\20\3\0\6\20\1\0"+
    "\4\20\1\103\23\20\20\0\3\20\3\0\6\20\1\0"+
    "\7\20\1\104\1\105\10\20\1\106\2\20\1\107\3\20"+
    "\20\0\3\20\3\0\6\20\1\0\26\20\1\110\1\20"+
    "\20\0\3\20\3\0\6\20\1\0\14\20\1\111\13\20"+
    "\20\0\3\20\3\0\6\20\1\0\15\20\1\112\12\20"+
    "\20\0\3\20\3\0\6\20\1\0\7\20\1\113\20\20"+
    "\24\0\1\10\40\0\1\10\2\41\1\0\1\41\1\114"+
    "\1\41\1\44\24\41\1\45\31\41\2\42\1\0\1\42"+
    "\1\43\1\42\1\115\24\42\1\116\31\42\2\43\1\0"+
    "\3\43\1\117\24\43\1\120\31\43\2\121\1\0\1\121"+
    "\1\122\1\121\1\123\60\121\1\0\1\121\1\122\1\121"+
    "\1\124\24\121\1\41\1\121\1\41\3\121\1\41\6\121"+
    "\1\41\2\121\1\41\1\121\1\41\7\121\1\46\2\0"+
    "\1\46\1\0\61\46\2\0\1\46\1\0\12\46\3\47"+
    "\43\46\2\50\1\125\1\50\1\125\5\50\1\126\52\50"+
    "\2\51\3\0\60\51\17\0\3\127\60\0\1\52\1\0"+
    "\2\53\1\54\5\0\1\130\1\0\1\56\6\0\1\130"+
    "\5\0\1\56\35\0\2\131\1\54\5\0\1\130\10\0"+
    "\1\130\24\0\13\132\2\0\2\132\3\0\43\132\15\0"+
    "\1\52\1\0\3\131\43\0\17\133\3\134\3\133\3\134"+
    "\4\133\6\134\23\133\17\135\3\127\43\135\15\0\1\60"+
    "\1\0\3\61\3\0\2\62\1\136\1\62\1\64\1\62"+
    "\1\0\4\62\1\136\5\62\1\64\15\62\20\0\3\62"+
    "\3\0\6\62\1\0\30\62\1\0\13\132\2\0\2\132"+
    "\3\62\3\132\6\137\1\132\30\137\1\132\15\0\1\52"+
    "\1\0\3\140\3\0\6\62\1\0\30\62\20\0\3\20"+
    "\3\0\6\20\1\0\21\20\1\141\6\20\20\0\3\20"+
    "\3\0\6\20\1\0\4\20\1\142\23\20\20\0\3\20"+
    "\3\0\6\20\1\0\20\20\1\143\7\20\20\0\3\20"+
    "\3\0\6\20\1\0\1\77\27\20\20\0\3\20\3\0"+
    "\6\20\1\0\14\20\1\144\13\20\20\0\3\20\3\0"+
    "\6\20\1\0\5\20\1\145\22\20\20\0\3\20\3\0"+
    "\6\20\1\0\22\20\1\146\5\20\20\0\3\20\3\0"+
    "\6\20\1\0\22\20\1\147\5\20\20\0\3\20\3\0"+
    "\6\20\1\0\21\20\1\150\6\20\20\0\3\20\3\0"+
    "\6\20\1\0\15\20\1\151\12\20\20\0\3\20\3\0"+
    "\6\20\1\0\17\20\1\100\10\20\20\0\3\20\3\0"+
    "\6\20\1\0\21\20\1\100\6\20\20\0\3\20\3\0"+
    "\6\20\1\0\14\20\1\152\13\20\20\0\3\20\3\0"+
    "\6\20\1\0\6\20\1\153\12\20\1\154\6\20\20\0"+
    "\3\20\3\0\6\20\1\0\15\20\1\155\12\20\20\0"+
    "\3\20\3\0\6\20\1\0\6\20\1\156\20\20\1\157"+
    "\20\0\3\20\3\0\6\20\1\0\1\160\16\20\1\161"+
    "\10\20\20\0\3\20\3\0\6\20\1\0\10\20\1\162"+
    "\17\20\20\0\3\20\3\0\6\20\1\0\16\20\1\163"+
    "\11\20\20\0\3\20\3\0\6\20\1\0\10\20\1\164"+
    "\7\20\1\165\7\20\20\0\3\20\3\0\6\20\1\0"+
    "\10\20\1\166\1\20\1\167\15\20\20\0\3\20\3\0"+
    "\6\20\1\0\10\20\1\170\17\20\1\0\2\114\1\0"+
    "\3\114\1\171\24\114\1\172\31\114\2\173\1\0\1\173"+
    "\1\0\62\173\1\0\1\173\1\0\1\173\1\42\24\173"+
    "\1\42\1\173\1\42\3\173\1\42\6\173\1\42\2\173"+
    "\1\42\1\173\1\42\7\173\6\0\1\43\24\0\1\43"+
    "\1\0\1\43\3\0\1\43\6\0\1\43\2\0\1\43"+
    "\1\0\1\43\7\0\2\122\1\0\3\122\1\174\56\122"+
    "\12\125\1\175\52\125\2\50\1\125\1\50\1\125\5\50"+
    "\1\126\3\50\1\176\46\50\17\0\3\127\4\0\1\117"+
    "\1\130\7\0\1\117\1\130\1\117\36\0\2\177\2\0"+
    "\3\200\62\0\3\131\5\0\1\130\10\0\1\130\24\0"+
    "\17\133\3\0\3\133\3\0\4\133\6\0\23\133\15\0"+
    "\1\52\1\0\3\201\3\0\3\134\1\0\1\56\2\0"+
    "\6\134\4\0\1\56\16\0\17\135\3\0\43\135\13\132"+
    "\2\177\2\132\3\202\3\132\6\137\1\132\30\137\1\132"+
    "\17\0\3\140\3\0\2\62\1\203\3\62\1\0\4\62"+
    "\1\203\23\62\20\0\3\20\3\0\6\20\1\0\15\20"+
    "\1\100\12\20\20\0\3\20\3\0\6\20\1\0\1\204"+
    "\27\20\20\0\3\20\3\0\6\20\1\0\4\20\1\100"+
    "\23\20\20\0\3\20\3\0\6\20\1\0\20\20\1\101"+
    "\1\205\6\20\20\0\3\20\3\0\6\20\1\0\1\206"+
    "\27\20\20\0\3\20\3\0\6\20\1\0\1\20\1\170"+
    "\26\20\20\0\3\20\3\0\6\20\1\0\13\20\1\100"+
    "\14\20\20\0\3\20\3\0\6\20\1\0\4\20\1\207"+
    "\23\20\20\0\3\20\3\0\6\20\1\0\1\101\27\20"+
    "\20\0\3\20\3\0\6\20\1\0\6\20\1\100\21\20"+
    "\20\0\3\20\3\0\6\20\1\0\10\20\1\210\17\20"+
    "\20\0\3\20\3\0\6\20\1\0\22\20\1\207\5\20"+
    "\20\0\3\20\3\0\6\20\1\0\17\20\1\101\10\20"+
    "\20\0\3\20\3\0\6\20\1\0\14\20\1\211\13\20"+
    "\20\0\3\20\3\0\6\20\1\0\4\20\1\212\23\20"+
    "\20\0\3\20\3\0\6\20\1\0\21\20\1\213\6\20"+
    "\20\0\3\20\3\0\6\20\1\0\22\20\1\214\5\20"+
    "\20\0\3\20\3\0\6\20\1\0\21\20\1\215\6\20"+
    "\20\0\3\20\3\0\6\20\1\0\4\20\1\216\23\20"+
    "\20\0\3\20\3\0\6\20\1\0\15\20\1\217\12\20"+
    "\20\0\3\20\3\0\6\20\1\0\10\20\1\220\17\20"+
    "\20\0\3\20\3\0\6\20\1\0\3\20\1\100\24\20"+
    "\20\0\3\20\3\0\6\20\1\0\1\221\27\20\20\0"+
    "\3\20\3\0\6\20\1\0\12\20\1\143\15\20\1\0"+
    "\2\122\1\0\3\122\1\222\24\122\1\114\1\122\1\114"+
    "\3\122\1\114\6\122\1\114\2\122\1\114\1\122\1\114"+
    "\7\122\12\125\1\175\3\125\1\223\46\125\2\224\1\0"+
    "\1\224\1\0\60\224\17\0\3\200\62\0\3\200\4\0"+
    "\1\117\10\0\1\117\1\0\1\117\40\0\1\52\1\0"+
    "\3\201\3\0\2\134\1\225\1\0\1\56\2\0\4\134"+
    "\1\225\1\134\4\0\1\56\35\0\3\202\3\0\1\62"+
    "\1\226\4\62\1\0\3\62\1\226\1\62\1\226\22\62"+
    "\14\0\2\177\2\0\3\202\3\0\6\62\1\0\30\62"+
    "\20\0\3\20\3\0\6\20\1\0\11\20\1\100\16\20"+
    "\20\0\3\20\3\0\6\20\1\0\10\20\1\227\17\20"+
    "\20\0\3\20\3\0\6\20\1\0\22\20\1\230\5\20"+
    "\20\0\3\20\3\0\6\20\1\0\17\20\1\217\10\20"+
    "\20\0\3\20\3\0\6\20\1\0\20\20\1\231\7\20"+
    "\20\0\3\20\3\0\6\20\1\0\4\20\1\166\23\20"+
    "\20\0\3\20\3\0\6\20\1\0\15\20\1\232\12\20"+
    "\20\0\3\20\3\0\6\20\1\0\10\20\1\233\17\20"+
    "\20\0\3\20\3\0\6\20\1\0\2\20\1\101\25\20"+
    "\20\0\3\20\3\0\6\20\1\0\2\20\1\234\25\20"+
    "\20\0\3\20\3\0\6\20\1\0\3\20\1\235\24\20"+
    "\20\0\3\20\3\0\6\20\1\0\14\20\1\100\13\20"+
    "\20\0\3\20\3\0\6\20\1\0\6\20\1\156\21\20"+
    "\20\0\3\20\3\0\6\20\1\0\21\20\1\113\6\20"+
    "\14\0\2\177\1\52\1\0\3\201\3\0\3\134\1\0"+
    "\1\56\2\0\6\134\4\0\1\56\35\0\3\20\3\0"+
    "\6\20\1\0\14\20\1\236\13\20\20\0\3\20\3\0"+
    "\6\20\1\0\12\20\1\101\15\20\20\0\3\20\3\0"+
    "\6\20\1\0\21\20\1\237\6\20\20\0\3\20\3\0"+
    "\6\20\1\0\5\20\1\100\22\20\20\0\3\20\3\0"+
    "\6\20\1\0\2\20\1\100\25\20\20\0\3\20\3\0"+
    "\6\20\1\0\7\20\1\100\20\20\20\0\3\20\3\0"+
    "\6\20\1\0\4\20\1\232\23\20\20\0\3\20\3\0"+
    "\6\20\1\0\22\20\1\143\5\20\20\0\3\20\3\0"+
    "\6\20\1\0\4\20\1\77\23\20\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7632];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\1\11\32\1\1\0\6\1\1\0"+
    "\2\1\1\0\1\1\2\0\33\1\1\0\2\1\1\11"+
    "\1\0\1\1\1\0\2\1\1\0\2\1\2\0\1\11"+
    "\37\1\1\0\2\1\1\0\1\1\1\0\23\1\1\11"+
    "\14\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[159];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    TokenList tokenList = TokenList.getInstance();
    ErrorList errorList = ErrorList.getInstance();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public SimpleLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { errorList.insertError(ERROR, "Desconocido -> " + yytext(),  yyline);
            }
            // fall through
          case 16: break;
          case 2:
            { /* ignore */
            }
            // fall through
          case 17: break;
          case 3:
            { tokenList.insertToken(OPERADOR, yytext(), yyline);
            }
            // fall through
          case 18: break;
          case 4:
            { errorList.insertError(ERROR, "String no cerrado -> " + yytext(), yyline);
            }
            // fall through
          case 19: break;
          case 5:
            { tokenList.insertToken(ERROR, yytext(), yyline);
            }
            // fall through
          case 20: break;
          case 6:
            { tokenList.insertToken(LITERAL, yytext(), yyline);
            }
            // fall through
          case 21: break;
          case 7:
            { tokenList.insertToken(IDENTIFICADOR, yytext(),  yyline);
            }
            // fall through
          case 22: break;
          case 8:
            { tokenList.insertToken(ERROR, "Error: Comentario no cerrado -> " + yytext(), yyline);
            }
            // fall through
          case 23: break;
          case 9:
            { errorList.insertError(ERROR, "Octal mal formado -> " + yytext(), yyline);
            }
            // fall through
          case 24: break;
          case 10:
            { errorList.insertError(ERROR,"Identificador no puede empezar con un número -> " + yytext(), yyline);
            }
            // fall through
          case 25: break;
          case 11:
            { tokenList.insertToken(PALABRA_RESERVADA, yytext(), yyline);
            }
            // fall through
          case 26: break;
          case 12:
            { errorList.insertError(ERROR, "String no valido -> " + yytext(), yyline);
            }
            // fall through
          case 27: break;
          case 13:
            { errorList.insertError(ERROR, "Exponente mal formado -> " + yytext(), yyline);
            }
            // fall through
          case 28: break;
          case 14:
            { errorList.insertError(ERROR, "Hexadecimal mal formado -> " + yytext(), yyline);
            }
            // fall through
          case 29: break;
          case 15:
            { errorList.insertError(ERROR, "Flotante mal formado -> " + yytext(), yyline);
            }
            // fall through
          case 30: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
