/* The following code was generated by JFlex 1.4.3 on 31/8/24, 4:07 p. m. */

/* Simple JFlex example to tokenize arithmetic expressions */

package com.compi.scanner;
import static com.compi.scanner.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 31/8/24, 4:07 p. m. from the specification file
 * <tt>C:/Users/vmrjo/Documents/GitHub/Scanner/Scanner/src/main/java/com/compi/scanner/SimpleLexer.flex</tt>
 */
public class SimpleLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\5\2\0\1\3\22\0\1\3\1\45\1\50\1\52"+
    "\1\0\1\45\1\47\1\0\1\37\1\37\1\6\1\40\1\37\1\41"+
    "\1\37\1\4\12\2\1\37\1\37\1\44\1\42\1\43\1\37\1\0"+
    "\32\1\1\37\1\51\1\37\1\45\2\0\1\7\1\13\1\17\1\24"+
    "\1\15\1\25\1\31\1\21\1\23\1\1\1\16\1\26\1\27\1\22"+
    "\1\12\1\35\1\1\1\14\1\20\1\11\1\10\1\36\1\33\1\30"+
    "\1\34\1\32\1\37\1\46\1\37\1\37\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\2\4\17\2\7\4"+
    "\1\1\2\5\1\0\1\3\1\0\17\2\2\6\6\2"+
    "\1\0\1\7\1\0\1\5\1\7\1\0\30\2\1\0"+
    "\2\5\27\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\53\0\254\0\327\0\u0102"+
    "\0\u012d\0\u0158\0\u0183\0\u01ae\0\u01d9\0\u0204\0\u022f\0\u025a"+
    "\0\u0285\0\u02b0\0\u02db\0\u0306\0\u0331\0\u035c\0\53\0\u0387"+
    "\0\u03b2\0\u03dd\0\u0408\0\u0433\0\u045e\0\u0489\0\u04b4\0\u04df"+
    "\0\201\0\u050a\0\u0535\0\u0560\0\u058b\0\u05b6\0\u05e1\0\u060c"+
    "\0\u0637\0\u0662\0\u068d\0\u06b8\0\u06e3\0\u070e\0\u0739\0\u0764"+
    "\0\u078f\0\u07ba\0\126\0\u07e5\0\u0810\0\u083b\0\u0866\0\u0891"+
    "\0\u08bc\0\u08e7\0\u0489\0\u0912\0\u093d\0\u0968\0\u04b4\0\u0993"+
    "\0\u09be\0\u09e9\0\u0a14\0\u0a3f\0\u0a6a\0\u0a95\0\u0ac0\0\u0aeb"+
    "\0\u0b16\0\u0b41\0\u0b6c\0\u0b97\0\u0bc2\0\u0bed\0\u0c18\0\u0c43"+
    "\0\u0c6e\0\u0c99\0\u0cc4\0\u0cef\0\u0d1a\0\u0d45\0\u0d70\0\u0d9b"+
    "\0\u0912\0\u0912\0\u0489\0\u0dc6\0\u0df1\0\u0e1c\0\u0e47\0\u0e72"+
    "\0\u0e9d\0\u0ec8\0\u0ef3\0\u0f1e\0\u0f49\0\u0f74\0\u0f9f\0\u0fca"+
    "\0\u0ff5\0\u1020\0\u104b\0\u1076\0\u10a1\0\u10cc\0\u10f7\0\u1122"+
    "\0\u114d\0\u1178";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\5\1\7\1\10"+
    "\1\11\1\12\1\3\1\13\1\14\1\15\1\3\1\16"+
    "\1\17\2\3\1\20\1\21\1\22\1\23\2\3\1\24"+
    "\1\3\1\25\2\3\1\26\1\27\1\30\1\31\1\7"+
    "\1\32\1\33\1\7\1\34\1\35\1\36\1\2\1\37"+
    "\54\0\2\3\4\0\30\3\15\0\1\40\1\41\4\0"+
    "\30\40\20\0\1\42\1\0\1\43\33\0\1\27\52\0"+
    "\1\27\11\0\2\3\4\0\1\3\1\44\26\3\15\0"+
    "\2\3\4\0\13\3\1\45\14\3\15\0\2\3\4\0"+
    "\25\3\1\46\2\3\15\0\2\3\4\0\5\3\1\47"+
    "\22\3\15\0\2\3\4\0\6\3\1\50\21\3\15\0"+
    "\2\3\4\0\13\3\1\51\3\3\1\52\1\3\1\53"+
    "\6\3\15\0\2\3\4\0\1\52\2\3\1\54\6\3"+
    "\1\55\15\3\15\0\2\3\4\0\2\3\1\56\7\3"+
    "\1\57\1\3\1\60\7\3\1\61\3\3\15\0\2\3"+
    "\4\0\13\3\1\62\2\3\1\63\11\3\15\0\2\3"+
    "\4\0\3\3\1\64\2\3\1\65\21\3\15\0\2\3"+
    "\4\0\3\3\1\66\13\3\1\67\10\3\15\0\2\3"+
    "\4\0\3\3\1\70\24\3\15\0\2\3\4\0\3\3"+
    "\1\44\24\3\15\0\2\3\4\0\12\3\1\71\15\3"+
    "\15\0\2\3\4\0\3\3\1\72\24\3\54\0\1\27"+
    "\1\0\1\27\51\0\3\27\51\0\1\27\1\7\51\0"+
    "\1\27\1\0\1\7\50\0\1\27\3\0\1\27\46\0"+
    "\1\27\4\0\1\27\3\0\5\73\1\0\42\73\1\74"+
    "\1\75\1\73\2\76\1\77\1\0\1\76\1\0\45\76"+
    "\1\0\2\40\4\0\30\40\14\0\5\42\1\0\45\42"+
    "\6\43\1\100\44\43\1\0\2\3\4\0\2\3\1\101"+
    "\25\3\15\0\2\3\4\0\11\3\1\102\2\3\1\103"+
    "\13\3\15\0\2\3\4\0\26\3\1\104\1\3\15\0"+
    "\2\3\4\0\6\3\1\105\21\3\15\0\2\3\4\0"+
    "\2\3\1\106\17\3\1\107\5\3\15\0\2\3\4\0"+
    "\1\3\1\110\26\3\15\0\2\3\4\0\11\3\1\111"+
    "\16\3\15\0\2\3\4\0\2\3\1\112\25\3\15\0"+
    "\2\3\4\0\13\3\1\113\14\3\15\0\2\3\4\0"+
    "\1\66\27\3\15\0\2\3\4\0\1\114\4\3\1\115"+
    "\22\3\15\0\2\3\4\0\3\3\1\116\24\3\15\0"+
    "\2\3\4\0\22\3\1\117\1\120\4\3\15\0\2\3"+
    "\4\0\14\3\1\121\13\3\15\0\2\3\4\0\2\3"+
    "\1\63\25\3\15\0\2\3\4\0\1\3\1\122\26\3"+
    "\15\0\2\3\4\0\16\3\1\123\11\3\15\0\2\3"+
    "\4\0\5\3\1\63\22\3\15\0\2\3\4\0\3\3"+
    "\1\124\24\3\15\0\2\3\4\0\13\3\1\125\14\3"+
    "\15\0\2\3\4\0\14\3\1\126\13\3\15\0\2\3"+
    "\4\0\14\3\1\127\2\3\1\130\10\3\14\0\5\131"+
    "\1\0\42\131\1\132\7\131\1\0\3\131\1\73\1\131"+
    "\2\73\5\131\1\73\2\131\1\73\22\131\1\133\1\73"+
    "\1\131\3\76\1\0\1\76\1\0\45\76\4\43\1\5"+
    "\1\43\1\100\44\43\1\0\2\3\4\0\3\3\1\63"+
    "\24\3\15\0\2\3\4\0\14\3\1\134\13\3\15\0"+
    "\2\3\4\0\3\3\1\135\24\3\15\0\2\3\4\0"+
    "\6\3\1\136\21\3\15\0\2\3\4\0\1\137\27\3"+
    "\15\0\2\3\4\0\1\3\1\140\26\3\15\0\2\3"+
    "\4\0\14\3\1\141\13\3\15\0\2\3\4\0\20\3"+
    "\1\63\7\3\15\0\2\3\4\0\6\3\1\63\21\3"+
    "\15\0\2\3\4\0\6\3\1\140\21\3\15\0\2\3"+
    "\4\0\2\3\1\142\6\3\1\62\16\3\15\0\2\3"+
    "\4\0\2\3\1\143\25\3\15\0\2\3\4\0\1\3"+
    "\1\144\26\3\15\0\2\3\4\0\5\3\1\62\22\3"+
    "\15\0\2\3\4\0\13\3\1\145\14\3\15\0\2\3"+
    "\4\0\6\3\1\146\21\3\15\0\2\3\4\0\2\3"+
    "\1\147\25\3\15\0\2\3\4\0\4\3\1\126\23\3"+
    "\15\0\2\3\4\0\1\150\27\3\15\0\2\3\4\0"+
    "\1\62\27\3\15\0\2\3\4\0\22\3\1\63\5\3"+
    "\15\0\2\3\4\0\17\3\1\111\10\3\15\0\2\3"+
    "\4\0\15\3\1\63\12\3\15\0\2\3\4\0\1\151"+
    "\27\3\15\0\2\3\4\0\22\3\1\117\5\3\15\0"+
    "\2\3\4\0\13\3\1\63\14\3\15\0\2\3\4\0"+
    "\15\3\1\152\12\3\15\0\2\3\4\0\7\3\1\63"+
    "\20\3\15\0\2\3\4\0\5\3\1\135\22\3\15\0"+
    "\2\3\4\0\11\3\1\153\16\3\15\0\2\3\4\0"+
    "\14\3\1\154\13\3\15\0\2\3\4\0\14\3\1\155"+
    "\13\3\15\0\2\3\4\0\10\3\1\62\17\3\15\0"+
    "\2\3\4\0\6\3\1\127\21\3\15\0\2\3\4\0"+
    "\3\3\1\156\24\3\15\0\2\3\4\0\10\3\1\157"+
    "\17\3\15\0\2\3\4\0\1\3\1\160\26\3\15\0"+
    "\2\3\4\0\2\3\1\71\25\3\15\0\2\3\4\0"+
    "\6\3\1\156\21\3\15\0\2\3\4\0\2\3\1\161"+
    "\25\3\15\0\2\3\4\0\13\3\1\162\14\3\15\0"+
    "\2\3\4\0\10\3\1\63\17\3\15\0\2\3\4\0"+
    "\16\3\1\63\11\3\15\0\2\3\4\0\12\3\1\63"+
    "\15\3\15\0\2\3\4\0\17\3\1\62\10\3\15\0"+
    "\2\3\4\0\6\3\1\66\21\3\15\0\2\3\4\0"+
    "\1\3\1\111\26\3\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4515];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\21\1\1\11\11\1\1\0"+
    "\1\1\1\0\27\1\1\0\1\1\1\0\2\1\1\0"+
    "\30\1\1\0\31\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public SimpleLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public SimpleLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 134) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { return new Token(ERROR, yytext(),  yyline);
          }
        case 8: break;
        case 3: 
          { /* ignore */
          }
        case 9: break;
        case 5: 
          { return new Token(ERROR, yytext(), yyline);
          }
        case 10: break;
        case 2: 
          { return new Token(IDENTIFICADOR, yytext(),  yyline);
          }
        case 11: break;
        case 4: 
          { return new Token(OPERADOR, yytext(), yyline);
          }
        case 12: break;
        case 6: 
          { return new Token(PALABRA_RESERVADA, yytext(), yyline);
          }
        case 13: break;
        case 7: 
          { return new Token(LITERAL, yytext(), yyline);
          }
        case 14: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
