
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compi.scanner;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 8;
  public static final int CONTINUE = 31;
  public static final int LT = 18;
  public static final int ELSE = 23;
  public static final int PLUS = 6;
  public static final int INT = 32;
  public static final int TYPE_LONG = 26;
  public static final int RPAREN = 12;
  public static final int WHILE = 24;
  public static final int SEMI = 10;
  public static final int TYPE_INT = 25;
  public static final int PLUS_PLUS = 20;
  public static final int TYPE_CHAR = 28;
  public static final int TRUE = 3;
  public static final int IF = 22;
  public static final int GT = 17;
  public static final int LPAREN = 11;
  public static final int LBRACKET = 13;
  public static final int ID = 2;
  public static final int RBRACKET = 14;
  public static final int COMMA = 15;
  public static final int FLOAT = 33;
  public static final int EOF = 0;
  public static final int BREAK = 30;
  public static final int DIV = 9;
  public static final int FALSE = 4;
  public static final int MINUS = 7;
  public static final int error = 1;
  public static final int EQ = 5;
  public static final int MINUS_MINUS = 21;
  public static final int VOID = 29;
  public static final int EQ_EQ = 16;
  public static final int NOT_EQ = 19;
  public static final int TYPE_SHORT = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "TRUE",
  "FALSE",
  "EQ",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "SEMI",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "COMMA",
  "EQ_EQ",
  "GT",
  "LT",
  "NOT_EQ",
  "PLUS_PLUS",
  "MINUS_MINUS",
  "IF",
  "ELSE",
  "WHILE",
  "TYPE_INT",
  "TYPE_LONG",
  "TYPE_SHORT",
  "TYPE_CHAR",
  "VOID",
  "BREAK",
  "CONTINUE",
  "INT",
  "FLOAT"
  };
}

