
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compi.scanner;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIV_EQ = 36;
  public static final int LBRACKET = 23;
  public static final int CONST = 8;
  public static final int CHAR = 7;
  public static final int MINUS_MINUS = 38;
  public static final int CASE = 47;
  public static final int LPAREN = 21;
  public static final int SEMI = 20;
  public static final int CONTINUE = 4;
  public static final int INT = 5;
  public static final int FOR = 44;
  public static final int MINUS = 17;
  public static final int WRITE = 11;
  public static final int RPAREN = 22;
  public static final int NOT = 41;
  public static final int AND = 40;
  public static final int TIMES_EQ = 35;
  public static final int LT_EQ = 30;
  public static final int LT = 31;
  public static final int OR = 39;
  public static final int COMMA = 25;
  public static final int DIV = 19;
  public static final int TYPE_LONG = 50;
  public static final int TYPE_INT = 49;
  public static final int PLUS = 16;
  public static final int IF = 42;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int RETURN = 55;
  public static final int PLUS_PLUS = 37;
  public static final int RBRACKET = 24;
  public static final int TRUE = 13;
  public static final int error = 1;
  public static final int MOD = 9;
  public static final int BREAK = 3;
  public static final int VOID = 53;
  public static final int EQ = 15;
  public static final int TYPE_CHAR = 52;
  public static final int SWITCH = 46;
  public static final int TIMES = 18;
  public static final int GT_EQ = 28;
  public static final int COLON = 26;
  public static final int ELSE = 43;
  public static final int READ = 12;
  public static final int NOT_EQ = 32;
  public static final int WHILE = 45;
  public static final int DEFAULT = 48;
  public static final int FLOAT = 6;
  public static final int STRING = 10;
  public static final int PLUS_EQ = 33;
  public static final int TYPE_SHORT = 51;
  public static final int MINUS_EQ = 34;
  public static final int FALSE = 14;
  public static final int GT = 29;
  public static final int DO = 54;
  public static final int EQ_EQ = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "BREAK",
  "CONTINUE",
  "INT",
  "FLOAT",
  "CHAR",
  "CONST",
  "MOD",
  "STRING",
  "WRITE",
  "READ",
  "TRUE",
  "FALSE",
  "EQ",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "SEMI",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "COMMA",
  "COLON",
  "EQ_EQ",
  "GT_EQ",
  "GT",
  "LT_EQ",
  "LT",
  "NOT_EQ",
  "PLUS_EQ",
  "MINUS_EQ",
  "TIMES_EQ",
  "DIV_EQ",
  "PLUS_PLUS",
  "MINUS_MINUS",
  "OR",
  "AND",
  "NOT",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "TYPE_INT",
  "TYPE_LONG",
  "TYPE_SHORT",
  "TYPE_CHAR",
  "VOID",
  "DO",
  "RETURN"
  };
}

